// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: `${string}://${string}` | (string & {});
};

/**
 * Body_import_kaggle_csv_api_v1_import_kaggle_post
 */
export type BodyImportKaggleCsvApiV1ImportKagglePost = {
    /**
     * File
     *
     * Kaggle CSV file to import
     */
    file: Blob | File;
};

/**
 * CatalogEntry
 *
 * A sample catalog entry.
 *
 * Attributes:
 * id (int): Stable integer identifier.
 * name (str): Fragrance name.
 * brand (str): Fragrance house / brand.
 * notes (list[str]): Accord / top / heart / base notes.
 */
export type CatalogEntry = {
    /**
     * Id
     *
     * Stable integer identifier.
     */
    id: number;
    /**
     * Name
     *
     * Fragrance name.
     */
    name: string;
    /**
     * Brand
     *
     * Fragrance house or brand.
     */
    brand: string;
    /**
     * Notes
     *
     * Accord notes.
     */
    notes?: Array<string>;
};

/**
 * CatalogListResponse
 *
 * Paginated-style response for ``GET /fragrances``.
 *
 * Attributes:
 * items (list[CatalogEntry]): Catalog entries.
 * total (int): Total entries available.
 */
export type CatalogListResponse = {
    /**
     * Items
     *
     * Catalog entries.
     */
    items?: Array<CatalogEntry>;
    /**
     * Total
     *
     * Total entries available.
     */
    total: number;
};

/**
 * CheckpointInput
 *
 * External model outputs retain their actual units and algorithm.
 */
export type CheckpointInput = {
    /**
     * Algorithm Version
     */
    algorithm_version: string;
    /**
     * Predictions
     */
    predictions?: Array<{
        [key: string]: string | number | null;
    }>;
};

/**
 * EnrollmentInput
 *
 * Recorder identity is independent of whose palate is measured.
 */
export type EnrollmentInput = {
    /**
     * Reviewer Id
     */
    reviewer_id: string;
    /**
     * Recorder Usernames
     */
    recorder_usernames: Array<string>;
    /**
     * Session Size
     */
    session_size?: number;
};

/**
 * EvaluationCreate
 *
 * Schema for creating a new evaluation.
 */
export type EvaluationCreate = {
    /**
     * Fragrance Id
     */
    fragrance_id: string;
    /**
     * Reviewer Id
     */
    reviewer_id: string;
    /**
     * Rating
     */
    rating: number;
    /**
     * Notes
     */
    notes?: string | null;
    /**
     * Longevity Rating
     */
    longevity_rating?: number | null;
    /**
     * Sillage Rating
     */
    sillage_rating?: number | null;
    /**
     * Worn By Reviewer Id
     *
     * ADR-011: reviewer the fragrance was worn by, when this rating is an "on others" opinion (e.g. a partner's reaction) rather than "on me". Omit or leave null for the default self-worn rating. Must differ from reviewer_id.
     */
    worn_by_reviewer_id?: string | null;
    /**
     * Evaluated At
     *
     * Encounter time; timezone-naive inputs are interpreted as UTC.
     */
    evaluated_at?: string | null;
};

/**
 * EvaluationResponse
 *
 * Schema for evaluation response.
 */
export type EvaluationResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Fragrance Id
     */
    fragrance_id: string;
    /**
     * Reviewer Id
     */
    reviewer_id: string;
    /**
     * Rating
     */
    rating: number;
    /**
     * Notes
     */
    notes: string | null;
    /**
     * Longevity Rating
     */
    longevity_rating: number | null;
    /**
     * Sillage Rating
     */
    sillage_rating: number | null;
    /**
     * Worn By Reviewer Id
     */
    worn_by_reviewer_id?: string | null;
    /**
     * Evaluated At
     */
    evaluated_at: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Recorded By
     */
    recorded_by?: string | null;
};

/**
 * EvaluationUpdate
 *
 * Schema for updating an evaluation (PATCH semantics).
 *
 * Every field defaults to `None` so a client can omit it to mean "leave
 * unchanged"; `evaluation_service.update()` reads only the fields present
 * in the request via `model_dump(exclude_unset=True)`. `notes`,
 * `longevity_rating`, `sillage_rating`, and `worn_by_reviewer_id` back
 * nullable columns (`Evaluation.notes`/`longevity_rating`/
 * `sillage_rating`/`worn_by_reviewer_id`), so an explicit `null` for one
 * of those is legitimate: for `worn_by_reviewer_id` it reverts the rating
 * to the default "on me" perspective. `rating` backs a NOT NULL column
 * and is additionally guarded below so an explicit `null` is rejected
 * rather than reaching the database layer.
 *
 * `worn_by_reviewer_id` cannot be validated against `reviewer_id` here
 * (this schema has no `reviewer_id` field -- it is immutable via PATCH),
 * so that self-reference check and the existence check both happen at
 * the API layer (api/evaluations.py), which already has the stored
 * evaluation's `reviewer_id` on hand.
 */
export type EvaluationUpdate = {
    /**
     * Rating
     */
    rating?: number | null;
    /**
     * Notes
     */
    notes?: string | null;
    /**
     * Longevity Rating
     */
    longevity_rating?: number | null;
    /**
     * Sillage Rating
     */
    sillage_rating?: number | null;
    /**
     * Worn By Reviewer Id
     *
     * ADR-011: reviewer the fragrance was worn by, when this rating is an "on others" opinion (e.g. a partner's reaction) rather than "on me". Omit or leave null for the default self-worn rating. Must differ from reviewer_id.
     */
    worn_by_reviewer_id?: string | null;
};

/**
 * ExplanationResponse
 *
 * Response model for recommendation explanation.
 */
export type ExplanationResponse = {
    /**
     * Fragrance Id
     */
    fragrance_id: string;
    /**
     * Fragrance Name
     */
    fragrance_name: string;
    /**
     * Explanation
     */
    explanation: string;
    /**
     * Model
     *
     * Model used to generate explanation
     */
    model: string;
    /**
     * Cached
     *
     * Whether response was cached
     */
    cached?: boolean;
};

/**
 * FragranceAccordCreate
 *
 * Schema for creating a fragrance accord.
 */
export type FragranceAccordCreate = {
    /**
     * Accord Type
     */
    accord_type: string;
    /**
     * Intensity
     */
    intensity: number;
};

/**
 * FragranceAccordResponse
 *
 * Schema for fragrance accord response.
 */
export type FragranceAccordResponse = {
    /**
     * Accord Type
     */
    accord_type: string;
    /**
     * Intensity
     */
    intensity: number;
};

/**
 * FragranceCreate
 *
 * Schema for creating a new fragrance.
 */
export type FragranceCreate = {
    /**
     * Name
     */
    name: string;
    /**
     * Brand
     */
    brand: string;
    /**
     * Concentration
     */
    concentration: string;
    /**
     * Version Key
     */
    version_key?: string;
    /**
     * Launch Year
     */
    launch_year?: number | null;
    /**
     * Gender Target
     */
    gender_target?: 'Masculine' | 'Feminine' | 'Unisex';
    /**
     * Primary Family
     */
    primary_family: string;
    /**
     * Subfamily
     */
    subfamily: string;
    /**
     * Intensity
     */
    intensity?: string | null;
    /**
     * Notes
     */
    notes?: Array<FragranceNoteCreate>;
    /**
     * Accords
     */
    accords?: Array<FragranceAccordCreate>;
};

/**
 * FragranceNoteCreate
 *
 * Schema for creating a fragrance-note association.
 */
export type FragranceNoteCreate = {
    /**
     * Note Name
     */
    note_name: string;
    /**
     * Note Category
     */
    note_category: string;
    /**
     * Position
     */
    position: 'top' | 'heart' | 'flat' | 'base';
};

/**
 * FragranceNoteResponse
 *
 * Schema for fragrance-note response.
 */
export type FragranceNoteResponse = {
    note: NoteResponse;
    /**
     * Position
     */
    position: string;
};

/**
 * FragranceResponse
 *
 * Schema for fragrance response.
 */
export type FragranceResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Brand
     */
    brand: string;
    /**
     * Concentration
     */
    concentration: string;
    /**
     * Version Key
     */
    version_key: string;
    /**
     * Launch Year
     */
    launch_year: number | null;
    /**
     * Gender Target
     */
    gender_target: string;
    /**
     * Primary Family
     */
    primary_family: string;
    /**
     * Subfamily
     */
    subfamily: string;
    /**
     * Intensity
     */
    intensity: string | null;
    /**
     * Data Source
     */
    data_source: string;
    /**
     * External Id
     */
    external_id: string | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
    /**
     * Notes
     */
    notes?: Array<FragranceNoteResponse>;
    /**
     * Accords
     */
    accords?: Array<FragranceAccordResponse>;
};

/**
 * FragranceUpdate
 *
 * Schema for updating a fragrance (PATCH semantics).
 *
 * Every field defaults to `None` so a client can omit it to mean "leave
 * unchanged"; `fragrance_service.update()` reads only the fields present
 * in the request via `model_dump(exclude_unset=True)`. `launch_year` and
 * `intensity` back nullable columns (`Fragrance.launch_year`/`intensity`),
 * so an explicit `null` for one of those is legitimate and clears it.
 * `name`, `brand`, `concentration`, `gender_target`, `primary_family`, and
 * `subfamily` all back NOT NULL columns and are additionally guarded below
 * so an explicit `null` for any of them is rejected rather than reaching
 * the database layer.
 */
export type FragranceUpdate = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Brand
     */
    brand?: string | null;
    /**
     * Concentration
     */
    concentration?: string | null;
    /**
     * Launch Year
     */
    launch_year?: number | null;
    /**
     * Gender Target
     */
    gender_target?: 'Masculine' | 'Feminine' | 'Unisex' | null;
    /**
     * Primary Family
     */
    primary_family?: string | null;
    /**
     * Subfamily
     */
    subfamily?: string | null;
    /**
     * Intensity
     */
    intensity?: string | null;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * HealthStatus
 *
 * Health check response model.
 */
export type HealthStatus = {
    /**
     * Status
     *
     * Overall status: ok, degraded, or error
     */
    status: string;
    /**
     * Timestamp
     *
     * Unix timestamp
     */
    timestamp?: number;
    /**
     * Uptime Seconds
     *
     * Application uptime in seconds
     */
    uptime_seconds: number;
    /**
     * Version
     *
     * Application version
     */
    version?: string;
    /**
     * Python Version
     */
    python_version?: string;
};

/**
 * ImportResponse
 *
 * Response model for import operations.
 */
export type ImportResponse = {
    /**
     * Total Rows
     *
     * Total rows processed
     */
    total_rows: number;
    /**
     * Imported
     *
     * Successfully imported count
     */
    imported: number;
    /**
     * Skipped
     *
     * Skipped rows count
     */
    skipped: number;
    /**
     * Errors
     *
     * Error messages
     */
    errors?: Array<string>;
};

/**
 * ImpressionView
 *
 * Candidate and immutable ranking information shown to an evaluator.
 */
export type ImpressionView = {
    /**
     * Id
     */
    id: string;
    /**
     * Fragrance Id
     */
    fragrance_id: string;
    /**
     * Fragrance Name
     */
    fragrance_name: string;
    /**
     * Fragrance Brand
     */
    fragrance_brand: string;
    /**
     * Rank
     */
    rank: number;
    /**
     * Score Type
     */
    score_type: string;
    /**
     * Score Value
     */
    score_value: number;
    /**
     * Match Percent
     */
    match_percent: number;
    /**
     * Shown At
     */
    shown_at: string;
    /**
     * Responses
     */
    responses?: Array<ResponseView>;
};

/**
 * MembershipInput
 *
 * Require exact catalog ID and documented identity verification.
 */
export type MembershipInput = {
    /**
     * Fragrance Id
     */
    fragrance_id: string;
    /**
     * Role
     */
    role: 'UNIVERSAL_BASELINE' | 'HIDDEN_REPEAT' | 'HOLDOUT' | 'ACTIVE_LEARNING' | 'RETEST' | 'OWNED_VALIDATION' | 'OTHER';
    /**
     * Repeat Of Id
     */
    repeat_of_id?: string | null;
    /**
     * Group Name
     */
    group_name?: string;
    /**
     * Selection
     */
    selection?: {
        [key: string]: string | number | null;
    };
    /**
     * Identity Evidence
     */
    identity_evidence: string;
    /**
     * Gtin
     */
    gtin?: string | null;
};

/**
 * MetricsView
 *
 * Explicit counts and denominators for recommendation outcomes.
 */
export type MetricsView = {
    /**
     * Reviewer Id
     */
    reviewer_id: string;
    /**
     * Window Start
     */
    window_start: string;
    /**
     * Window End
     */
    window_end: string;
    /**
     * Reviewer Population
     */
    reviewer_population: Array<string>;
    /**
     * Exclusion Policy
     */
    exclusion_policy: Array<string>;
    /**
     * Excluded Impressions
     */
    excluded_impressions: number;
    /**
     * Algorithm Versions
     */
    algorithm_versions: Array<string>;
    /**
     * Candidate Strategies
     */
    candidate_strategies: Array<string>;
    /**
     * Run Filters
     */
    run_filters: Array<{
        [key: string]: unknown;
    }>;
    /**
     * Source Snapshots
     */
    source_snapshots: Array<{
        [key: string]: unknown;
    }>;
    /**
     * Eligible Impressions
     */
    eligible_impressions: number;
    /**
     * Explicit Interest Responses
     */
    explicit_interest_responses: number;
    /**
     * Positive Interest Responses
     */
    positive_interest_responses: number;
    /**
     * Response Coverage
     */
    response_coverage: number | null;
    /**
     * Interest Rate
     */
    interest_rate: number | null;
    /**
     * Sampled Recommendations
     */
    sampled_recommendations: number;
    /**
     * Sampling Conversion
     */
    sampling_conversion: number | null;
    /**
     * Linked Outcomes
     */
    linked_outcomes: number;
    /**
     * Mean Ordinary Rating
     */
    mean_ordinary_rating: number | null;
    /**
     * Would Wear Positive
     */
    would_wear_positive: number;
    /**
     * Would Wear Responses
     */
    would_wear_responses: number;
    /**
     * Would Buy Positive
     */
    would_buy_positive: number;
    /**
     * Would Buy Responses
     */
    would_buy_responses: number;
    /**
     * Unique Brands
     */
    unique_brands: number;
    /**
     * Unavailable Candidates
     */
    unavailable_candidates: number;
    /**
     * Llm Call Count
     */
    llm_call_count: number;
    /**
     * Llm Cache Hits
     */
    llm_cache_hits: number;
    /**
     * Llm Failures
     */
    llm_failures: number;
    /**
     * Mean Llm Latency Ms
     */
    mean_llm_latency_ms: number | null;
    /**
     * Llm Calls With Known Estimated Cost
     */
    llm_calls_with_known_estimated_cost: number;
    /**
     * Known Estimated Cost Usd
     */
    known_estimated_cost_usd: number | null;
    /**
     * Llm Calls With Known Provider Cost
     */
    llm_calls_with_known_provider_cost: number;
    /**
     * Known Provider Cost Usd
     */
    known_provider_cost_usd: number | null;
    /**
     * Connectivity Failures
     */
    connectivity_failures: number;
    /**
     * Manual Recoveries
     */
    manual_recoveries: number;
};

/**
 * NoteResponse
 *
 * Schema for note response.
 */
export type NoteResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Category
     */
    category: string;
    /**
     * Subcategory
     */
    subcategory: string | null;
};

/**
 * OperationalEventCreate
 *
 * Pilot connectivity or manual-recovery observation.
 */
export type OperationalEventCreate = {
    /**
     * Reviewer Id
     */
    reviewer_id: string;
    /**
     * Event Type
     */
    event_type: 'CONNECTIVITY_FAILURE' | 'MANUAL_RECOVERY';
    /**
     * Details
     */
    details?: string | null;
};

/**
 * PredictionCreate
 *
 * Freeze one model's predicted rating before the real outcome exists.
 */
export type PredictionCreate = {
    /**
     * Reviewer Id
     */
    reviewer_id: string;
    /**
     * Fragrance Id
     */
    fragrance_id: string;
    /**
     * Checkpoint Id
     */
    checkpoint_id?: string | null;
    /**
     * Model Id
     */
    model_id: string;
    /**
     * Model Version
     */
    model_version: string;
    /**
     * Feature Snapshot Version
     */
    feature_snapshot_version?: string | null;
    /**
     * Predicted Scale
     */
    predicted_scale?: string;
    /**
     * Predicted Rating
     */
    predicted_rating?: number | null;
    /**
     * Uncertainty
     */
    uncertainty?: number | null;
    /**
     * Percentile Rank
     */
    percentile_rank?: number | null;
    /**
     * Scenario
     */
    scenario?: string | null;
    /**
     * Input Manifest
     */
    input_manifest?: Array<{
        [key: string]: unknown;
    }>;
    /**
     * Explanation
     */
    explanation?: {
        [key: string]: unknown;
    } | null;
};

export type PredictionOutcomeInput = unknown & {
    /**
     * Outcome Evaluation Id
     */
    outcome_evaluation_id?: string | null;
    /**
     * Outcome Observation Id
     */
    outcome_observation_id?: string | null;
};

/**
 * PredictionView
 *
 * Serialized, (mostly) immutable prediction snapshot.
 *
 * Every field is set once at creation except ``outcome_evaluation_id``,
 * ``outcome_observation_id``, ``outcome_linked_at``, and
 * ``outcome_recorded_by``, which start NULL and are set exactly once by a
 * later, separate outcome-link call.
 */
export type PredictionView = {
    /**
     * Id
     */
    id: string;
    /**
     * Reviewer Id
     */
    reviewer_id: string;
    /**
     * Fragrance Id
     */
    fragrance_id: string;
    /**
     * Checkpoint Id
     */
    checkpoint_id: string | null;
    /**
     * Model Id
     */
    model_id: string;
    /**
     * Model Version
     */
    model_version: string;
    /**
     * Feature Snapshot Version
     */
    feature_snapshot_version: string | null;
    /**
     * Predicted Scale
     */
    predicted_scale: string;
    /**
     * Predicted Rating
     */
    predicted_rating: number | null;
    /**
     * Uncertainty
     */
    uncertainty: number | null;
    /**
     * Percentile Rank
     */
    percentile_rank: number | null;
    /**
     * Scenario
     */
    scenario: string | null;
    /**
     * Input Manifest
     */
    input_manifest: Array<{
        [key: string]: unknown;
    }>;
    /**
     * Explanation
     */
    explanation: {
        [key: string]: unknown;
    } | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Recorded By
     */
    recorded_by: string | null;
    /**
     * Outcome Evaluation Id
     */
    outcome_evaluation_id: string | null;
    /**
     * Outcome Observation Id
     */
    outcome_observation_id: string | null;
    /**
     * Outcome Linked At
     */
    outcome_linked_at: string | null;
    /**
     * Outcome Recorded By
     */
    outcome_recorded_by: string | null;
};

/**
 * ProfileSummaryResponse
 *
 * Response model for reviewer preference profile summary.
 */
export type ProfileSummaryResponse = {
    /**
     * Reviewer Id
     */
    reviewer_id: string;
    /**
     * Evaluation Count
     */
    evaluation_count: number;
    /**
     * Top Liked Notes
     *
     * Top 5 liked notes with scores
     */
    top_liked_notes?: Array<[
        string,
        number
    ]>;
    /**
     * Top Disliked Notes
     *
     * Top 5 disliked notes with scores
     */
    top_disliked_notes?: Array<[
        string,
        number
    ]>;
    /**
     * Top Accords
     *
     * Top 5 preferred accords
     */
    top_accords?: Array<[
        string,
        number
    ]>;
    /**
     * Top Families
     *
     * Top 5 preferred fragrance families
     */
    top_families?: Array<[
        string,
        number
    ]>;
    /**
     * Llm Summary
     *
     * LLM-generated natural language summary
     */
    llm_summary?: string | null;
};

/**
 * ProgramInput
 *
 * Versioned program definition.
 */
export type ProgramInput = {
    /**
     * Name
     */
    name: string;
    /**
     * Version
     */
    version: string;
    /**
     * Description
     */
    description?: string | null;
};

/**
 * RatingRequest
 *
 * Request body for ``POST /ratings``.
 *
 * Attributes:
 * name (str): Fragrance name (required).
 * brand (str | None): Fragrance house or brand. Improves rating accuracy.
 * description (str): Free-text description of the scent profile.
 * notes (list[FragranceNote] | None): Optional list of accord/top/heart/base notes.
 */
export type RatingRequest = {
    /**
     * Name
     *
     * Fragrance name, e.g. 'Aventus'.
     */
    name: string;
    /**
     * Brand
     *
     * Fragrance house or brand, e.g. 'Creed'.
     */
    brand?: string | null;
    /**
     * Description
     *
     * Free-text description of the scent. Mention projection, longevity, season, and accords for a better rating.
     */
    description: string;
    /**
     * Notes
     *
     * Optional list of fragrance notes. Capped at 32 entries of up to 64 characters each to bound prompt size and upstream cost.
     */
    notes?: Array<string> | null;
};

/**
 * RatingResponse
 *
 * Response body returned by ``POST /ratings``.
 *
 * Attributes:
 * score (int): Integer rating, 1 (poor) to 10 (excellent).
 * reasoning (str): Human-readable explanation written by the LLM.
 * model (str): Identifier of the LLM that produced the rating.
 * notes (list[str]): Echo of accord notes used by the model.
 * latency_warning (str): Reminder that LLM latency is variable.
 */
export type RatingResponse = {
    /**
     * Score
     *
     * Rating from 1 (poor) to 10 (excellent).
     */
    score: number;
    /**
     * Reasoning
     *
     * LLM-authored explanation of the score.
     */
    reasoning: string;
    /**
     * Model
     *
     * LLM model identifier (e.g. 'anthropic/claude-3.5-sonnet').
     */
    model: string;
    /**
     * Notes
     *
     * Accord notes used in the rating.
     */
    notes?: Array<string>;
    /**
     * Latency Warning
     *
     * Operational note about response time variability.
     */
    latency_warning?: string;
};

/**
 * ReadinessCheck
 *
 * Individual dependency check result.
 */
export type ReadinessCheck = {
    /**
     * Name
     *
     * Dependency name
     */
    name: string;
    /**
     * Status
     *
     * Check passed
     */
    status: boolean;
    /**
     * Latency Ms
     *
     * Check latency in milliseconds
     */
    latency_ms?: number | null;
    /**
     * Error
     *
     * Error message if failed
     */
    error?: string | null;
};

/**
 * ReadinessStatus
 *
 * Readiness check response with dependency details.
 */
export type ReadinessStatus = {
    /**
     * Status
     *
     * Overall status: ok, degraded, or error
     */
    status: string;
    /**
     * Timestamp
     *
     * Unix timestamp
     */
    timestamp?: number;
    /**
     * Uptime Seconds
     *
     * Application uptime in seconds
     */
    uptime_seconds: number;
    /**
     * Version
     *
     * Application version
     */
    version?: string;
    /**
     * Python Version
     */
    python_version?: string;
    /**
     * Checks
     *
     * Individual dependency checks
     */
    checks?: {
        [key: string]: ReadinessCheck;
    };
};

/**
 * RecommendationListResponse
 *
 * Response model for recommendation list.
 */
export type RecommendationListResponse = {
    /**
     * Reviewer Id
     */
    reviewer_id: string;
    /**
     * Recommendations
     */
    recommendations: Array<RecommendationResponse>;
    /**
     * Count
     */
    count: number;
};

/**
 * RecommendationResponse
 *
 * Response model for a single recommendation.
 */
export type RecommendationResponse = {
    /**
     * Fragrance Id
     */
    fragrance_id: string;
    /**
     * Fragrance Name
     */
    fragrance_name: string;
    /**
     * Fragrance Brand
     */
    fragrance_brand: string;
    /**
     * Match Score
     *
     * Match score from 0.0 to 1.0
     */
    match_score: number;
    /**
     * Match Percent
     *
     * Match score as percentage 0-100
     */
    match_percent: number;
    /**
     * Vetoed
     *
     * Whether fragrance contains a disliked note
     */
    vetoed?: boolean;
    /**
     * Veto Reason
     *
     * Reason for veto if applicable
     */
    veto_reason?: string | null;
};

/**
 * ResponseCreate
 *
 * Complete latest feedback state; submission appends a revision.
 */
export type ResponseCreate = {
    /**
     * Interested
     */
    interested?: boolean | null;
    /**
     * Sampling State
     */
    sampling_state?: 'PLANNED' | 'ACQUIRED' | 'SAMPLED' | 'UNAVAILABLE' | null;
    /**
     * Unavailable Reason
     */
    unavailable_reason?: string | null;
    /**
     * Outcome Evaluation Id
     */
    outcome_evaluation_id?: string | null;
    /**
     * Outcome Observation Id
     */
    outcome_observation_id?: string | null;
    /**
     * Would Wear
     */
    would_wear?: boolean | null;
    /**
     * Would Buy
     */
    would_buy?: boolean | null;
};

/**
 * ResponseInput
 *
 * A submitted timepoint; null means unanswered, zero is a response.
 */
export type ResponseInput = {
    /**
     * Stage
     */
    stage: 'BLOTTER' | 'SKIN';
    /**
     * Elapsed Minutes
     */
    elapsed_minutes?: number;
    /**
     * Detected
     */
    detected?: boolean | null;
    /**
     * Intensity
     */
    intensity?: number | null;
    /**
     * Liking
     */
    liking?: number | null;
    /**
     * Confidence
     */
    confidence?: number | null;
    /**
     * Sweetness
     */
    sweetness?: number | null;
    /**
     * Freshness
     */
    freshness?: number | null;
    /**
     * Density
     */
    density?: number | null;
    /**
     * Familiarity
     */
    familiarity?: number | null;
    /**
     * Dryness
     */
    dryness?: number | null;
    /**
     * Clean Soapy
     */
    clean_soapy?: number | null;
    /**
     * Earthy Rooty
     */
    earthy_rooty?: number | null;
    /**
     * Bodily Animalic
     */
    bodily_animalic?: number | null;
    /**
     * Discomfort
     */
    discomfort?: number | null;
    /**
     * Opening Liking
     */
    opening_liking?: number | null;
    /**
     * Drydown Liking
     */
    drydown_liking?: number | null;
    /**
     * Would Wear
     */
    would_wear?: number | null;
    /**
     * Would Buy
     */
    would_buy?: number | null;
    /**
     * Artistic Appreciation
     */
    artistic_appreciation?: number | null;
    /**
     * Projection
     */
    projection?: number | null;
    /**
     * Longevity Minutes
     */
    longevity_minutes?: number | null;
    /**
     * Perceived Notes
     */
    perceived_notes?: Array<string> | null;
    /**
     * Likes
     */
    likes?: string | null;
    /**
     * Dislikes
     */
    dislikes?: string | null;
    /**
     * Reminds Me Of
     */
    reminds_me_of?: string | null;
    /**
     * Comments
     */
    comments?: string | null;
};

/**
 * ResponseView
 *
 * Stored append-only feedback revision.
 */
export type ResponseView = {
    /**
     * Interested
     */
    interested?: boolean | null;
    /**
     * Sampling State
     */
    sampling_state?: 'PLANNED' | 'ACQUIRED' | 'SAMPLED' | 'UNAVAILABLE' | null;
    /**
     * Unavailable Reason
     */
    unavailable_reason?: string | null;
    /**
     * Outcome Evaluation Id
     */
    outcome_evaluation_id?: string | null;
    /**
     * Outcome Observation Id
     */
    outcome_observation_id?: string | null;
    /**
     * Would Wear
     */
    would_wear?: boolean | null;
    /**
     * Would Buy
     */
    would_buy?: boolean | null;
    /**
     * Id
     */
    id: string;
    /**
     * Impression Id
     */
    impression_id: string;
    /**
     * Revision
     */
    revision: number;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Recorded By
     */
    recorded_by: string | null;
};

/**
 * ReviewerCreate
 *
 * Schema for creating a new reviewer.
 */
export type ReviewerCreate = {
    /**
     * Name
     */
    name: string;
};

/**
 * ReviewerResponse
 *
 * Schema for reviewer response.
 */
export type ReviewerResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Evaluation Count
     */
    evaluation_count?: number;
};

/**
 * RunCreate
 *
 * Parameters that produce a new persisted recommendation run.
 */
export type RunCreate = {
    /**
     * Reviewer Id
     */
    reviewer_id: string;
    /**
     * Limit
     */
    limit?: number;
    /**
     * Exclude Rated
     */
    exclude_rated?: boolean;
    /**
     * Candidate Strategy
     */
    candidate_strategy?: 'catalog-affinity';
};

/**
 * RunView
 *
 * A recommendation run and its already-persisted impressions.
 */
export type RunView = {
    /**
     * Id
     */
    id: string;
    /**
     * Reviewer Id
     */
    reviewer_id: string;
    /**
     * Algorithm Version
     */
    algorithm_version: string;
    /**
     * Candidate Strategy
     */
    candidate_strategy: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Impressions
     */
    impressions: Array<ImpressionView>;
};

/**
 * SkinPlanInput
 *
 * Explicit reason, including low confidence or low-rated controls.
 */
export type SkinPlanInput = {
    /**
     * Reason
     */
    reason: string;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

export type LivenessHealthLiveGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health/live';
};

export type LivenessHealthLiveGetResponses = {
    /**
     * Successful Response
     */
    200: HealthStatus;
};

export type LivenessHealthLiveGetResponse = LivenessHealthLiveGetResponses[keyof LivenessHealthLiveGetResponses];

export type ReadinessHealthReadyGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health/ready';
};

export type ReadinessHealthReadyGetErrors = {
    /**
     * Application is not ready (dependencies unavailable)
     */
    503: unknown;
};

export type ReadinessHealthReadyGetResponses = {
    /**
     * Application is ready to serve traffic
     */
    200: ReadinessStatus;
};

export type ReadinessHealthReadyGetResponse = ReadinessHealthReadyGetResponses[keyof ReadinessHealthReadyGetResponses];

export type StartupHealthStartupGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health/startup';
};

export type StartupHealthStartupGetResponses = {
    /**
     * Successful Response
     */
    200: HealthStatus;
};

export type StartupHealthStartupGetResponse = StartupHealthStartupGetResponses[keyof StartupHealthStartupGetResponses];

export type CreateRatingRatingsPostData = {
    body: RatingRequest;
    headers?: {
        /**
         * X-Api-Key
         */
        'X-API-Key'?: string | null;
    };
    path?: never;
    query?: never;
    url: '/ratings';
};

export type CreateRatingRatingsPostErrors = {
    /**
     * Missing or invalid X-API-Key header. Required on this endpoint (see fragrance_rater.middleware.auth).
     */
    401: unknown;
    /**
     * Request body failed validation.
     */
    422: unknown;
    /**
     * Rate limit exceeded; retry after a short delay.
     */
    429: unknown;
    /**
     * LLM upstream is unavailable, or no household API key is configured for this deployment (FRAGRANCE_RATER_API_KEY unset).
     */
    503: unknown;
};

export type CreateRatingRatingsPostResponses = {
    /**
     * Rating produced successfully.
     */
    200: RatingResponse;
};

export type CreateRatingRatingsPostResponse = CreateRatingRatingsPostResponses[keyof CreateRatingRatingsPostResponses];

export type ListCatalogEntriesFragrancesGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/fragrances';
};

export type ListCatalogEntriesFragrancesGetResponses = {
    /**
     * Catalog returned.
     */
    200: CatalogListResponse;
};

export type ListCatalogEntriesFragrancesGetResponse = ListCatalogEntriesFragrancesGetResponses[keyof ListCatalogEntriesFragrancesGetResponses];

export type GetCatalogEntryFragrancesFragranceIdGetData = {
    body?: never;
    path: {
        /**
         * Fragrance Id
         */
        fragrance_id: number;
    };
    query?: never;
    url: '/fragrances/{fragrance_id}';
};

export type GetCatalogEntryFragrancesFragranceIdGetErrors = {
    /**
     * No fragrance with the given id.
     */
    404: unknown;
    /**
     * Path parameter failed validation.
     */
    422: unknown;
};

export type GetCatalogEntryFragrancesFragranceIdGetResponses = {
    /**
     * Fragrance found.
     */
    200: CatalogEntry;
};

export type GetCatalogEntryFragrancesFragranceIdGetResponse = GetCatalogEntryFragrancesFragranceIdGetResponses[keyof GetCatalogEntryFragrancesFragranceIdGetResponses];

export type ListFragrancesApiV1FragrancesGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Q
         *
         * Search query for name or brand
         */
        q?: string | null;
        /**
         * Brand
         *
         * Filter by brand
         */
        brand?: string | null;
        /**
         * Primary Family
         *
         * Filter by fragrance family
         */
        primary_family?: string | null;
        /**
         * Gender Target
         *
         * Filter by gender target
         */
        gender_target?: 'Masculine' | 'Feminine' | 'Unisex' | null;
        /**
         * Limit
         */
        limit?: number;
        /**
         * Offset
         */
        offset?: number;
    };
    url: '/api/v1/fragrances';
};

export type ListFragrancesApiV1FragrancesGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListFragrancesApiV1FragrancesGetError = ListFragrancesApiV1FragrancesGetErrors[keyof ListFragrancesApiV1FragrancesGetErrors];

export type ListFragrancesApiV1FragrancesGetResponses = {
    /**
     * Response List Fragrances Api V1 Fragrances Get
     *
     * Successful Response
     */
    200: Array<FragranceResponse>;
};

export type ListFragrancesApiV1FragrancesGetResponse = ListFragrancesApiV1FragrancesGetResponses[keyof ListFragrancesApiV1FragrancesGetResponses];

export type CreateFragranceApiV1FragrancesPostData = {
    body: FragranceCreate;
    path?: never;
    query?: never;
    url: '/api/v1/fragrances';
};

export type CreateFragranceApiV1FragrancesPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateFragranceApiV1FragrancesPostError = CreateFragranceApiV1FragrancesPostErrors[keyof CreateFragranceApiV1FragrancesPostErrors];

export type CreateFragranceApiV1FragrancesPostResponses = {
    /**
     * Successful Response
     */
    201: FragranceResponse;
};

export type CreateFragranceApiV1FragrancesPostResponse = CreateFragranceApiV1FragrancesPostResponses[keyof CreateFragranceApiV1FragrancesPostResponses];

export type DeleteFragranceApiV1FragrancesFragranceIdDeleteData = {
    body?: never;
    path: {
        /**
         * Fragrance Id
         */
        fragrance_id: string;
    };
    query?: never;
    url: '/api/v1/fragrances/{fragrance_id}';
};

export type DeleteFragranceApiV1FragrancesFragranceIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteFragranceApiV1FragrancesFragranceIdDeleteError = DeleteFragranceApiV1FragrancesFragranceIdDeleteErrors[keyof DeleteFragranceApiV1FragrancesFragranceIdDeleteErrors];

export type DeleteFragranceApiV1FragrancesFragranceIdDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteFragranceApiV1FragrancesFragranceIdDeleteResponse = DeleteFragranceApiV1FragrancesFragranceIdDeleteResponses[keyof DeleteFragranceApiV1FragrancesFragranceIdDeleteResponses];

export type GetFragranceApiV1FragrancesFragranceIdGetData = {
    body?: never;
    path: {
        /**
         * Fragrance Id
         */
        fragrance_id: string;
    };
    query?: never;
    url: '/api/v1/fragrances/{fragrance_id}';
};

export type GetFragranceApiV1FragrancesFragranceIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetFragranceApiV1FragrancesFragranceIdGetError = GetFragranceApiV1FragrancesFragranceIdGetErrors[keyof GetFragranceApiV1FragrancesFragranceIdGetErrors];

export type GetFragranceApiV1FragrancesFragranceIdGetResponses = {
    /**
     * Successful Response
     */
    200: FragranceResponse;
};

export type GetFragranceApiV1FragrancesFragranceIdGetResponse = GetFragranceApiV1FragrancesFragranceIdGetResponses[keyof GetFragranceApiV1FragrancesFragranceIdGetResponses];

export type UpdateFragranceApiV1FragrancesFragranceIdPatchData = {
    body: FragranceUpdate;
    path: {
        /**
         * Fragrance Id
         */
        fragrance_id: string;
    };
    query?: never;
    url: '/api/v1/fragrances/{fragrance_id}';
};

export type UpdateFragranceApiV1FragrancesFragranceIdPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateFragranceApiV1FragrancesFragranceIdPatchError = UpdateFragranceApiV1FragrancesFragranceIdPatchErrors[keyof UpdateFragranceApiV1FragrancesFragranceIdPatchErrors];

export type UpdateFragranceApiV1FragrancesFragranceIdPatchResponses = {
    /**
     * Successful Response
     */
    200: FragranceResponse;
};

export type UpdateFragranceApiV1FragrancesFragranceIdPatchResponse = UpdateFragranceApiV1FragrancesFragranceIdPatchResponses[keyof UpdateFragranceApiV1FragrancesFragranceIdPatchResponses];

export type ListReviewersApiV1ReviewersGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/reviewers';
};

export type ListReviewersApiV1ReviewersGetResponses = {
    /**
     * Response List Reviewers Api V1 Reviewers Get
     *
     * Successful Response
     */
    200: Array<ReviewerResponse>;
};

export type ListReviewersApiV1ReviewersGetResponse = ListReviewersApiV1ReviewersGetResponses[keyof ListReviewersApiV1ReviewersGetResponses];

export type CreateReviewerApiV1ReviewersPostData = {
    body: ReviewerCreate;
    path?: never;
    query?: never;
    url: '/api/v1/reviewers';
};

export type CreateReviewerApiV1ReviewersPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateReviewerApiV1ReviewersPostError = CreateReviewerApiV1ReviewersPostErrors[keyof CreateReviewerApiV1ReviewersPostErrors];

export type CreateReviewerApiV1ReviewersPostResponses = {
    /**
     * Successful Response
     */
    201: ReviewerResponse;
};

export type CreateReviewerApiV1ReviewersPostResponse = CreateReviewerApiV1ReviewersPostResponses[keyof CreateReviewerApiV1ReviewersPostResponses];

export type DeleteReviewerApiV1ReviewersReviewerIdDeleteData = {
    body?: never;
    path: {
        /**
         * Reviewer Id
         */
        reviewer_id: string;
    };
    query?: never;
    url: '/api/v1/reviewers/{reviewer_id}';
};

export type DeleteReviewerApiV1ReviewersReviewerIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteReviewerApiV1ReviewersReviewerIdDeleteError = DeleteReviewerApiV1ReviewersReviewerIdDeleteErrors[keyof DeleteReviewerApiV1ReviewersReviewerIdDeleteErrors];

export type DeleteReviewerApiV1ReviewersReviewerIdDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteReviewerApiV1ReviewersReviewerIdDeleteResponse = DeleteReviewerApiV1ReviewersReviewerIdDeleteResponses[keyof DeleteReviewerApiV1ReviewersReviewerIdDeleteResponses];

export type GetReviewerApiV1ReviewersReviewerIdGetData = {
    body?: never;
    path: {
        /**
         * Reviewer Id
         */
        reviewer_id: string;
    };
    query?: never;
    url: '/api/v1/reviewers/{reviewer_id}';
};

export type GetReviewerApiV1ReviewersReviewerIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetReviewerApiV1ReviewersReviewerIdGetError = GetReviewerApiV1ReviewersReviewerIdGetErrors[keyof GetReviewerApiV1ReviewersReviewerIdGetErrors];

export type GetReviewerApiV1ReviewersReviewerIdGetResponses = {
    /**
     * Successful Response
     */
    200: ReviewerResponse;
};

export type GetReviewerApiV1ReviewersReviewerIdGetResponse = GetReviewerApiV1ReviewersReviewerIdGetResponses[keyof GetReviewerApiV1ReviewersReviewerIdGetResponses];

export type SeedReviewersApiV1ReviewersSeedPostData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/reviewers/seed';
};

export type SeedReviewersApiV1ReviewersSeedPostResponses = {
    /**
     * Response Seed Reviewers Api V1 Reviewers Seed Post
     *
     * Successful Response
     */
    200: Array<ReviewerResponse>;
};

export type SeedReviewersApiV1ReviewersSeedPostResponse = SeedReviewersApiV1ReviewersSeedPostResponses[keyof SeedReviewersApiV1ReviewersSeedPostResponses];

export type ListEvaluationsApiV1EvaluationsGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Reviewer Id
         *
         * Filter by reviewer ID
         */
        reviewer_id?: string | null;
        /**
         * Fragrance Id
         *
         * Filter by fragrance ID
         */
        fragrance_id?: string | null;
    };
    url: '/api/v1/evaluations';
};

export type ListEvaluationsApiV1EvaluationsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListEvaluationsApiV1EvaluationsGetError = ListEvaluationsApiV1EvaluationsGetErrors[keyof ListEvaluationsApiV1EvaluationsGetErrors];

export type ListEvaluationsApiV1EvaluationsGetResponses = {
    /**
     * Response List Evaluations Api V1 Evaluations Get
     *
     * Successful Response
     */
    200: Array<EvaluationResponse>;
};

export type ListEvaluationsApiV1EvaluationsGetResponse = ListEvaluationsApiV1EvaluationsGetResponses[keyof ListEvaluationsApiV1EvaluationsGetResponses];

export type CreateEvaluationApiV1EvaluationsPostData = {
    body: EvaluationCreate;
    path?: never;
    query?: never;
    url: '/api/v1/evaluations';
};

export type CreateEvaluationApiV1EvaluationsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateEvaluationApiV1EvaluationsPostError = CreateEvaluationApiV1EvaluationsPostErrors[keyof CreateEvaluationApiV1EvaluationsPostErrors];

export type CreateEvaluationApiV1EvaluationsPostResponses = {
    /**
     * Successful Response
     */
    201: EvaluationResponse;
};

export type CreateEvaluationApiV1EvaluationsPostResponse = CreateEvaluationApiV1EvaluationsPostResponses[keyof CreateEvaluationApiV1EvaluationsPostResponses];

export type DeleteEvaluationApiV1EvaluationsEvaluationIdDeleteData = {
    body?: never;
    path: {
        /**
         * Evaluation Id
         */
        evaluation_id: string;
    };
    query?: never;
    url: '/api/v1/evaluations/{evaluation_id}';
};

export type DeleteEvaluationApiV1EvaluationsEvaluationIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteEvaluationApiV1EvaluationsEvaluationIdDeleteError = DeleteEvaluationApiV1EvaluationsEvaluationIdDeleteErrors[keyof DeleteEvaluationApiV1EvaluationsEvaluationIdDeleteErrors];

export type DeleteEvaluationApiV1EvaluationsEvaluationIdDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteEvaluationApiV1EvaluationsEvaluationIdDeleteResponse = DeleteEvaluationApiV1EvaluationsEvaluationIdDeleteResponses[keyof DeleteEvaluationApiV1EvaluationsEvaluationIdDeleteResponses];

export type GetEvaluationApiV1EvaluationsEvaluationIdGetData = {
    body?: never;
    path: {
        /**
         * Evaluation Id
         */
        evaluation_id: string;
    };
    query?: never;
    url: '/api/v1/evaluations/{evaluation_id}';
};

export type GetEvaluationApiV1EvaluationsEvaluationIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetEvaluationApiV1EvaluationsEvaluationIdGetError = GetEvaluationApiV1EvaluationsEvaluationIdGetErrors[keyof GetEvaluationApiV1EvaluationsEvaluationIdGetErrors];

export type GetEvaluationApiV1EvaluationsEvaluationIdGetResponses = {
    /**
     * Successful Response
     */
    200: EvaluationResponse;
};

export type GetEvaluationApiV1EvaluationsEvaluationIdGetResponse = GetEvaluationApiV1EvaluationsEvaluationIdGetResponses[keyof GetEvaluationApiV1EvaluationsEvaluationIdGetResponses];

export type UpdateEvaluationApiV1EvaluationsEvaluationIdPatchData = {
    body: EvaluationUpdate;
    path: {
        /**
         * Evaluation Id
         */
        evaluation_id: string;
    };
    query?: never;
    url: '/api/v1/evaluations/{evaluation_id}';
};

export type UpdateEvaluationApiV1EvaluationsEvaluationIdPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateEvaluationApiV1EvaluationsEvaluationIdPatchError = UpdateEvaluationApiV1EvaluationsEvaluationIdPatchErrors[keyof UpdateEvaluationApiV1EvaluationsEvaluationIdPatchErrors];

export type UpdateEvaluationApiV1EvaluationsEvaluationIdPatchResponses = {
    /**
     * Successful Response
     */
    200: EvaluationResponse;
};

export type UpdateEvaluationApiV1EvaluationsEvaluationIdPatchResponse = UpdateEvaluationApiV1EvaluationsEvaluationIdPatchResponses[keyof UpdateEvaluationApiV1EvaluationsEvaluationIdPatchResponses];

export type GetRecommendationsApiV1RecommendationsReviewerIdGetData = {
    body?: never;
    path: {
        /**
         * Reviewer Id
         */
        reviewer_id: string;
    };
    query?: {
        /**
         * Limit
         *
         * Maximum recommendations
         */
        limit?: number;
        /**
         * Exclude Rated
         *
         * Exclude already-rated fragrances
         */
        exclude_rated?: boolean;
    };
    url: '/api/v1/recommendations/{reviewer_id}';
};

export type GetRecommendationsApiV1RecommendationsReviewerIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetRecommendationsApiV1RecommendationsReviewerIdGetError = GetRecommendationsApiV1RecommendationsReviewerIdGetErrors[keyof GetRecommendationsApiV1RecommendationsReviewerIdGetErrors];

export type GetRecommendationsApiV1RecommendationsReviewerIdGetResponses = {
    /**
     * Successful Response
     */
    200: RecommendationListResponse;
};

export type GetRecommendationsApiV1RecommendationsReviewerIdGetResponse = GetRecommendationsApiV1RecommendationsReviewerIdGetResponses[keyof GetRecommendationsApiV1RecommendationsReviewerIdGetResponses];

export type GetProfileSummaryApiV1RecommendationsReviewerIdProfileGetData = {
    body?: never;
    headers?: {
        /**
         * X-Api-Key
         */
        'X-API-Key'?: string | null;
    };
    path: {
        /**
         * Reviewer Id
         */
        reviewer_id: string;
    };
    query?: {
        /**
         * Include Llm
         *
         * Include LLM-generated summary
         */
        include_llm?: boolean;
    };
    url: '/api/v1/recommendations/{reviewer_id}/profile';
};

export type GetProfileSummaryApiV1RecommendationsReviewerIdProfileGetErrors = {
    /**
     * Missing or invalid X-API-Key header. Required on this endpoint because it can trigger a billed LLM call (see fragrance_rater.middleware.auth).
     */
    401: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Rate limit exceeded; retry after a short delay.
     */
    429: unknown;
    /**
     * No household API key is configured for this deployment (FRAGRANCE_RATER_API_KEY unset).
     */
    503: unknown;
};

export type GetProfileSummaryApiV1RecommendationsReviewerIdProfileGetError = GetProfileSummaryApiV1RecommendationsReviewerIdProfileGetErrors[keyof GetProfileSummaryApiV1RecommendationsReviewerIdProfileGetErrors];

export type GetProfileSummaryApiV1RecommendationsReviewerIdProfileGetResponses = {
    /**
     * Successful Response
     */
    200: ProfileSummaryResponse;
};

export type GetProfileSummaryApiV1RecommendationsReviewerIdProfileGetResponse = GetProfileSummaryApiV1RecommendationsReviewerIdProfileGetResponses[keyof GetProfileSummaryApiV1RecommendationsReviewerIdProfileGetResponses];

export type GetRecommendationExplanationApiV1RecommendationsReviewerIdFragranceIdExplainGetData = {
    body?: never;
    headers?: {
        /**
         * X-Api-Key
         */
        'X-API-Key'?: string | null;
    };
    path: {
        /**
         * Reviewer Id
         */
        reviewer_id: string;
        /**
         * Fragrance Id
         */
        fragrance_id: string;
    };
    query?: never;
    url: '/api/v1/recommendations/{reviewer_id}/{fragrance_id}/explain';
};

export type GetRecommendationExplanationApiV1RecommendationsReviewerIdFragranceIdExplainGetErrors = {
    /**
     * Missing or invalid X-API-Key header. Required on this endpoint because it triggers a billed LLM call.
     */
    401: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Rate limit exceeded; retry after a short delay.
     */
    429: unknown;
    /**
     * No household API key is configured for this deployment (FRAGRANCE_RATER_API_KEY unset).
     */
    503: unknown;
};

export type GetRecommendationExplanationApiV1RecommendationsReviewerIdFragranceIdExplainGetError = GetRecommendationExplanationApiV1RecommendationsReviewerIdFragranceIdExplainGetErrors[keyof GetRecommendationExplanationApiV1RecommendationsReviewerIdFragranceIdExplainGetErrors];

export type GetRecommendationExplanationApiV1RecommendationsReviewerIdFragranceIdExplainGetResponses = {
    /**
     * Successful Response
     */
    200: ExplanationResponse;
};

export type GetRecommendationExplanationApiV1RecommendationsReviewerIdFragranceIdExplainGetResponse = GetRecommendationExplanationApiV1RecommendationsReviewerIdFragranceIdExplainGetResponses[keyof GetRecommendationExplanationApiV1RecommendationsReviewerIdFragranceIdExplainGetResponses];

export type CreateRunApiV1RecommendationMeasurementRunsPostData = {
    body: RunCreate;
    path?: never;
    query?: never;
    url: '/api/v1/recommendation-measurement/runs';
};

export type CreateRunApiV1RecommendationMeasurementRunsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateRunApiV1RecommendationMeasurementRunsPostError = CreateRunApiV1RecommendationMeasurementRunsPostErrors[keyof CreateRunApiV1RecommendationMeasurementRunsPostErrors];

export type CreateRunApiV1RecommendationMeasurementRunsPostResponses = {
    /**
     * Successful Response
     */
    201: RunView;
};

export type CreateRunApiV1RecommendationMeasurementRunsPostResponse = CreateRunApiV1RecommendationMeasurementRunsPostResponses[keyof CreateRunApiV1RecommendationMeasurementRunsPostResponses];

export type GetRunApiV1RecommendationMeasurementRunsRunIdGetData = {
    body?: never;
    path: {
        /**
         * Run Id
         */
        run_id: string;
    };
    query?: never;
    url: '/api/v1/recommendation-measurement/runs/{run_id}';
};

export type GetRunApiV1RecommendationMeasurementRunsRunIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetRunApiV1RecommendationMeasurementRunsRunIdGetError = GetRunApiV1RecommendationMeasurementRunsRunIdGetErrors[keyof GetRunApiV1RecommendationMeasurementRunsRunIdGetErrors];

export type GetRunApiV1RecommendationMeasurementRunsRunIdGetResponses = {
    /**
     * Successful Response
     */
    200: RunView;
};

export type GetRunApiV1RecommendationMeasurementRunsRunIdGetResponse = GetRunApiV1RecommendationMeasurementRunsRunIdGetResponses[keyof GetRunApiV1RecommendationMeasurementRunsRunIdGetResponses];

export type GetImpressionExplanationApiV1RecommendationMeasurementImpressionsImpressionIdExplanationGetData = {
    body?: never;
    path: {
        /**
         * Impression Id
         */
        impression_id: string;
    };
    query?: never;
    url: '/api/v1/recommendation-measurement/impressions/{impression_id}/explanation';
};

export type GetImpressionExplanationApiV1RecommendationMeasurementImpressionsImpressionIdExplanationGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Rate limit exceeded; retry after a short delay.
     */
    429: unknown;
};

export type GetImpressionExplanationApiV1RecommendationMeasurementImpressionsImpressionIdExplanationGetError = GetImpressionExplanationApiV1RecommendationMeasurementImpressionsImpressionIdExplanationGetErrors[keyof GetImpressionExplanationApiV1RecommendationMeasurementImpressionsImpressionIdExplanationGetErrors];

export type GetImpressionExplanationApiV1RecommendationMeasurementImpressionsImpressionIdExplanationGetResponses = {
    /**
     * Successful Response
     */
    200: ExplanationResponse;
};

export type GetImpressionExplanationApiV1RecommendationMeasurementImpressionsImpressionIdExplanationGetResponse = GetImpressionExplanationApiV1RecommendationMeasurementImpressionsImpressionIdExplanationGetResponses[keyof GetImpressionExplanationApiV1RecommendationMeasurementImpressionsImpressionIdExplanationGetResponses];

export type AppendResponseApiV1RecommendationMeasurementImpressionsImpressionIdResponsesPostData = {
    body: ResponseCreate;
    path: {
        /**
         * Impression Id
         */
        impression_id: string;
    };
    query?: never;
    url: '/api/v1/recommendation-measurement/impressions/{impression_id}/responses';
};

export type AppendResponseApiV1RecommendationMeasurementImpressionsImpressionIdResponsesPostErrors = {
    /**
     * Impression not found
     */
    404: unknown;
    /**
     * Measurement conflict
     */
    409: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AppendResponseApiV1RecommendationMeasurementImpressionsImpressionIdResponsesPostError = AppendResponseApiV1RecommendationMeasurementImpressionsImpressionIdResponsesPostErrors[keyof AppendResponseApiV1RecommendationMeasurementImpressionsImpressionIdResponsesPostErrors];

export type AppendResponseApiV1RecommendationMeasurementImpressionsImpressionIdResponsesPostResponses = {
    /**
     * Successful Response
     */
    201: ResponseView;
};

export type AppendResponseApiV1RecommendationMeasurementImpressionsImpressionIdResponsesPostResponse = AppendResponseApiV1RecommendationMeasurementImpressionsImpressionIdResponsesPostResponses[keyof AppendResponseApiV1RecommendationMeasurementImpressionsImpressionIdResponsesPostResponses];

export type MetricsApiV1RecommendationMeasurementReviewersReviewerIdMetricsGetData = {
    body?: never;
    path: {
        /**
         * Reviewer Id
         */
        reviewer_id: string;
    };
    query?: {
        /**
         * Window Start
         */
        window_start?: string | null;
        /**
         * Window End
         */
        window_end?: string | null;
    };
    url: '/api/v1/recommendation-measurement/reviewers/{reviewer_id}/metrics';
};

export type MetricsApiV1RecommendationMeasurementReviewersReviewerIdMetricsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type MetricsApiV1RecommendationMeasurementReviewersReviewerIdMetricsGetError = MetricsApiV1RecommendationMeasurementReviewersReviewerIdMetricsGetErrors[keyof MetricsApiV1RecommendationMeasurementReviewersReviewerIdMetricsGetErrors];

export type MetricsApiV1RecommendationMeasurementReviewersReviewerIdMetricsGetResponses = {
    /**
     * Successful Response
     */
    200: MetricsView;
};

export type MetricsApiV1RecommendationMeasurementReviewersReviewerIdMetricsGetResponse = MetricsApiV1RecommendationMeasurementReviewersReviewerIdMetricsGetResponses[keyof MetricsApiV1RecommendationMeasurementReviewersReviewerIdMetricsGetResponses];

export type OperationalEventsApiV1RecommendationMeasurementOperationalEventsGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Reviewer Id
         */
        reviewer_id?: string | null;
    };
    url: '/api/v1/recommendation-measurement/operational-events';
};

export type OperationalEventsApiV1RecommendationMeasurementOperationalEventsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type OperationalEventsApiV1RecommendationMeasurementOperationalEventsGetError = OperationalEventsApiV1RecommendationMeasurementOperationalEventsGetErrors[keyof OperationalEventsApiV1RecommendationMeasurementOperationalEventsGetErrors];

export type OperationalEventsApiV1RecommendationMeasurementOperationalEventsGetResponses = {
    /**
     * Response Operational Events Api V1 Recommendation Measurement Operational Events Get
     *
     * Successful Response
     */
    200: Array<{
        [key: string]: unknown;
    }>;
};

export type OperationalEventsApiV1RecommendationMeasurementOperationalEventsGetResponse = OperationalEventsApiV1RecommendationMeasurementOperationalEventsGetResponses[keyof OperationalEventsApiV1RecommendationMeasurementOperationalEventsGetResponses];

export type OperationalEventApiV1RecommendationMeasurementOperationalEventsPostData = {
    body: OperationalEventCreate;
    path?: never;
    query?: never;
    url: '/api/v1/recommendation-measurement/operational-events';
};

export type OperationalEventApiV1RecommendationMeasurementOperationalEventsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type OperationalEventApiV1RecommendationMeasurementOperationalEventsPostError = OperationalEventApiV1RecommendationMeasurementOperationalEventsPostErrors[keyof OperationalEventApiV1RecommendationMeasurementOperationalEventsPostErrors];

export type OperationalEventApiV1RecommendationMeasurementOperationalEventsPostResponses = {
    /**
     * Response Operational Event Api V1 Recommendation Measurement Operational Events Post
     *
     * Successful Response
     */
    201: {
        [key: string]: unknown;
    };
};

export type OperationalEventApiV1RecommendationMeasurementOperationalEventsPostResponse = OperationalEventApiV1RecommendationMeasurementOperationalEventsPostResponses[keyof OperationalEventApiV1RecommendationMeasurementOperationalEventsPostResponses];

export type OperationalStatusApiV1RecommendationMeasurementOperationalStatusGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/recommendation-measurement/operational-status';
};

export type OperationalStatusApiV1RecommendationMeasurementOperationalStatusGetResponses = {
    /**
     * Response Operational Status Api V1 Recommendation Measurement Operational Status Get
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type OperationalStatusApiV1RecommendationMeasurementOperationalStatusGetResponse = OperationalStatusApiV1RecommendationMeasurementOperationalStatusGetResponses[keyof OperationalStatusApiV1RecommendationMeasurementOperationalStatusGetResponses];

export type ImportKaggleCsvApiV1ImportKagglePostData = {
    body: BodyImportKaggleCsvApiV1ImportKagglePost;
    path?: never;
    query?: {
        /**
         * Dry Run
         */
        dry_run?: boolean;
    };
    url: '/api/v1/import/kaggle';
};

export type ImportKaggleCsvApiV1ImportKagglePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ImportKaggleCsvApiV1ImportKagglePostError = ImportKaggleCsvApiV1ImportKagglePostErrors[keyof ImportKaggleCsvApiV1ImportKagglePostErrors];

export type ImportKaggleCsvApiV1ImportKagglePostResponses = {
    /**
     * Successful Response
     */
    200: ImportResponse;
};

export type ImportKaggleCsvApiV1ImportKagglePostResponse = ImportKaggleCsvApiV1ImportKagglePostResponses[keyof ImportKaggleCsvApiV1ImportKagglePostResponses];

export type AccessApiV1CalibrationAccessGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/calibration/access';
};

export type AccessApiV1CalibrationAccessGetResponses = {
    /**
     * Response Access Api V1 Calibration Access Get
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type AccessApiV1CalibrationAccessGetResponse = AccessApiV1CalibrationAccessGetResponses[keyof AccessApiV1CalibrationAccessGetResponses];

export type ProgramsApiV1CalibrationProgramsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/calibration/programs';
};

export type ProgramsApiV1CalibrationProgramsGetResponses = {
    /**
     * Response Programs Api V1 Calibration Programs Get
     *
     * Successful Response
     */
    200: Array<{
        [key: string]: unknown;
    }>;
};

export type ProgramsApiV1CalibrationProgramsGetResponse = ProgramsApiV1CalibrationProgramsGetResponses[keyof ProgramsApiV1CalibrationProgramsGetResponses];

export type CreateProgramApiV1CalibrationProgramsPostData = {
    body: ProgramInput;
    path?: never;
    query?: never;
    url: '/api/v1/calibration/programs';
};

export type CreateProgramApiV1CalibrationProgramsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateProgramApiV1CalibrationProgramsPostError = CreateProgramApiV1CalibrationProgramsPostErrors[keyof CreateProgramApiV1CalibrationProgramsPostErrors];

export type CreateProgramApiV1CalibrationProgramsPostResponses = {
    /**
     * Response Create Program Api V1 Calibration Programs Post
     *
     * Successful Response
     */
    201: {
        [key: string]: string;
    };
};

export type CreateProgramApiV1CalibrationProgramsPostResponse = CreateProgramApiV1CalibrationProgramsPostResponses[keyof CreateProgramApiV1CalibrationProgramsPostResponses];

export type MembersApiV1CalibrationProgramsProgramIdMembersGetData = {
    body?: never;
    path: {
        /**
         * Program Id
         */
        program_id: string;
    };
    query?: never;
    url: '/api/v1/calibration/programs/{program_id}/members';
};

export type MembersApiV1CalibrationProgramsProgramIdMembersGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type MembersApiV1CalibrationProgramsProgramIdMembersGetError = MembersApiV1CalibrationProgramsProgramIdMembersGetErrors[keyof MembersApiV1CalibrationProgramsProgramIdMembersGetErrors];

export type MembersApiV1CalibrationProgramsProgramIdMembersGetResponses = {
    /**
     * Response Members Api V1 Calibration Programs  Program Id  Members Get
     *
     * Successful Response
     */
    200: Array<{
        [key: string]: unknown;
    }>;
};

export type MembersApiV1CalibrationProgramsProgramIdMembersGetResponse = MembersApiV1CalibrationProgramsProgramIdMembersGetResponses[keyof MembersApiV1CalibrationProgramsProgramIdMembersGetResponses];

export type AddMemberApiV1CalibrationProgramsProgramIdMembersPostData = {
    body: MembershipInput;
    path: {
        /**
         * Program Id
         */
        program_id: string;
    };
    query?: never;
    url: '/api/v1/calibration/programs/{program_id}/members';
};

export type AddMemberApiV1CalibrationProgramsProgramIdMembersPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AddMemberApiV1CalibrationProgramsProgramIdMembersPostError = AddMemberApiV1CalibrationProgramsProgramIdMembersPostErrors[keyof AddMemberApiV1CalibrationProgramsProgramIdMembersPostErrors];

export type AddMemberApiV1CalibrationProgramsProgramIdMembersPostResponses = {
    /**
     * Response Add Member Api V1 Calibration Programs  Program Id  Members Post
     *
     * Successful Response
     */
    201: {
        [key: string]: string;
    };
};

export type AddMemberApiV1CalibrationProgramsProgramIdMembersPostResponse = AddMemberApiV1CalibrationProgramsProgramIdMembersPostResponses[keyof AddMemberApiV1CalibrationProgramsProgramIdMembersPostResponses];

export type FragellaLookupApiV1CalibrationProgramsProgramIdMembersMembershipIdFragellaLookupPostData = {
    body?: never;
    path: {
        /**
         * Program Id
         */
        program_id: string;
        /**
         * Membership Id
         */
        membership_id: string;
    };
    query?: {
        /**
         * Query
         */
        query?: string | null;
    };
    url: '/api/v1/calibration/programs/{program_id}/members/{membership_id}/fragella-lookup';
};

export type FragellaLookupApiV1CalibrationProgramsProgramIdMembersMembershipIdFragellaLookupPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type FragellaLookupApiV1CalibrationProgramsProgramIdMembersMembershipIdFragellaLookupPostError = FragellaLookupApiV1CalibrationProgramsProgramIdMembersMembershipIdFragellaLookupPostErrors[keyof FragellaLookupApiV1CalibrationProgramsProgramIdMembersMembershipIdFragellaLookupPostErrors];

export type FragellaLookupApiV1CalibrationProgramsProgramIdMembersMembershipIdFragellaLookupPostResponses = {
    /**
     * Response Fragella Lookup Api V1 Calibration Programs  Program Id  Members  Membership Id  Fragella Lookup Post
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type FragellaLookupApiV1CalibrationProgramsProgramIdMembersMembershipIdFragellaLookupPostResponse = FragellaLookupApiV1CalibrationProgramsProgramIdMembersMembershipIdFragellaLookupPostResponses[keyof FragellaLookupApiV1CalibrationProgramsProgramIdMembersMembershipIdFragellaLookupPostResponses];

export type FragellaUsageApiV1CalibrationFragellaUsageGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/calibration/fragella/usage';
};

export type FragellaUsageApiV1CalibrationFragellaUsageGetResponses = {
    /**
     * Response Fragella Usage Api V1 Calibration Fragella Usage Get
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type FragellaUsageApiV1CalibrationFragellaUsageGetResponse = FragellaUsageApiV1CalibrationFragellaUsageGetResponses[keyof FragellaUsageApiV1CalibrationFragellaUsageGetResponses];

export type ActivateApiV1CalibrationProgramsProgramIdActivatePostData = {
    body?: never;
    path: {
        /**
         * Program Id
         */
        program_id: string;
    };
    query?: never;
    url: '/api/v1/calibration/programs/{program_id}/activate';
};

export type ActivateApiV1CalibrationProgramsProgramIdActivatePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ActivateApiV1CalibrationProgramsProgramIdActivatePostError = ActivateApiV1CalibrationProgramsProgramIdActivatePostErrors[keyof ActivateApiV1CalibrationProgramsProgramIdActivatePostErrors];

export type ActivateApiV1CalibrationProgramsProgramIdActivatePostResponses = {
    /**
     * Response Activate Api V1 Calibration Programs  Program Id  Activate Post
     *
     * Successful Response
     */
    200: {
        [key: string]: boolean;
    };
};

export type ActivateApiV1CalibrationProgramsProgramIdActivatePostResponse = ActivateApiV1CalibrationProgramsProgramIdActivatePostResponses[keyof ActivateApiV1CalibrationProgramsProgramIdActivatePostResponses];

export type EnrollApiV1CalibrationProgramsProgramIdEnrollPostData = {
    body: EnrollmentInput;
    path: {
        /**
         * Program Id
         */
        program_id: string;
    };
    query?: never;
    url: '/api/v1/calibration/programs/{program_id}/enroll';
};

export type EnrollApiV1CalibrationProgramsProgramIdEnrollPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type EnrollApiV1CalibrationProgramsProgramIdEnrollPostError = EnrollApiV1CalibrationProgramsProgramIdEnrollPostErrors[keyof EnrollApiV1CalibrationProgramsProgramIdEnrollPostErrors];

export type EnrollApiV1CalibrationProgramsProgramIdEnrollPostResponses = {
    /**
     * Response Enroll Api V1 Calibration Programs  Program Id  Enroll Post
     *
     * Successful Response
     */
    201: {
        [key: string]: string;
    };
};

export type EnrollApiV1CalibrationProgramsProgramIdEnrollPostResponse = EnrollApiV1CalibrationProgramsProgramIdEnrollPostResponses[keyof EnrollApiV1CalibrationProgramsProgramIdEnrollPostResponses];

export type EnrollmentsApiV1CalibrationEnrollmentsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/calibration/enrollments';
};

export type EnrollmentsApiV1CalibrationEnrollmentsGetResponses = {
    /**
     * Response Enrollments Api V1 Calibration Enrollments Get
     *
     * Successful Response
     */
    200: Array<{
        [key: string]: string;
    }>;
};

export type EnrollmentsApiV1CalibrationEnrollmentsGetResponse = EnrollmentsApiV1CalibrationEnrollmentsGetResponses[keyof EnrollmentsApiV1CalibrationEnrollmentsGetResponses];

export type ManagerEnrollmentsApiV1CalibrationManagerEnrollmentsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/calibration/manager/enrollments';
};

export type ManagerEnrollmentsApiV1CalibrationManagerEnrollmentsGetResponses = {
    /**
     * Response Manager Enrollments Api V1 Calibration Manager Enrollments Get
     *
     * Successful Response
     */
    200: Array<{
        [key: string]: unknown;
    }>;
};

export type ManagerEnrollmentsApiV1CalibrationManagerEnrollmentsGetResponse = ManagerEnrollmentsApiV1CalibrationManagerEnrollmentsGetResponses[keyof ManagerEnrollmentsApiV1CalibrationManagerEnrollmentsGetResponses];

export type EnrollmentApiV1CalibrationEnrollmentsEnrollmentIdGetData = {
    body?: never;
    path: {
        /**
         * Enrollment Id
         */
        enrollment_id: string;
    };
    query?: never;
    url: '/api/v1/calibration/enrollments/{enrollment_id}';
};

export type EnrollmentApiV1CalibrationEnrollmentsEnrollmentIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type EnrollmentApiV1CalibrationEnrollmentsEnrollmentIdGetError = EnrollmentApiV1CalibrationEnrollmentsEnrollmentIdGetErrors[keyof EnrollmentApiV1CalibrationEnrollmentsEnrollmentIdGetErrors];

export type EnrollmentApiV1CalibrationEnrollmentsEnrollmentIdGetResponses = {
    /**
     * Response Enrollment Api V1 Calibration Enrollments  Enrollment Id  Get
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type EnrollmentApiV1CalibrationEnrollmentsEnrollmentIdGetResponse = EnrollmentApiV1CalibrationEnrollmentsEnrollmentIdGetResponses[keyof EnrollmentApiV1CalibrationEnrollmentsEnrollmentIdGetResponses];

export type ObserveApiV1CalibrationPresentationsPresentationIdObservationsPostData = {
    body: ResponseInput;
    path: {
        /**
         * Presentation Id
         */
        presentation_id: string;
    };
    query?: never;
    url: '/api/v1/calibration/presentations/{presentation_id}/observations';
};

export type ObserveApiV1CalibrationPresentationsPresentationIdObservationsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ObserveApiV1CalibrationPresentationsPresentationIdObservationsPostError = ObserveApiV1CalibrationPresentationsPresentationIdObservationsPostErrors[keyof ObserveApiV1CalibrationPresentationsPresentationIdObservationsPostErrors];

export type ObserveApiV1CalibrationPresentationsPresentationIdObservationsPostResponses = {
    /**
     * Response Observe Api V1 Calibration Presentations  Presentation Id  Observations Post
     *
     * Successful Response
     */
    201: {
        [key: string]: string;
    };
};

export type ObserveApiV1CalibrationPresentationsPresentationIdObservationsPostResponse = ObserveApiV1CalibrationPresentationsPresentationIdObservationsPostResponses[keyof ObserveApiV1CalibrationPresentationsPresentationIdObservationsPostResponses];

export type PostRevealApiV1CalibrationPresentationsPresentationIdPostRevealPostData = {
    body: ResponseInput;
    path: {
        /**
         * Presentation Id
         */
        presentation_id: string;
    };
    query?: never;
    url: '/api/v1/calibration/presentations/{presentation_id}/post-reveal';
};

export type PostRevealApiV1CalibrationPresentationsPresentationIdPostRevealPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PostRevealApiV1CalibrationPresentationsPresentationIdPostRevealPostError = PostRevealApiV1CalibrationPresentationsPresentationIdPostRevealPostErrors[keyof PostRevealApiV1CalibrationPresentationsPresentationIdPostRevealPostErrors];

export type PostRevealApiV1CalibrationPresentationsPresentationIdPostRevealPostResponses = {
    /**
     * Response Post Reveal Api V1 Calibration Presentations  Presentation Id  Post Reveal Post
     *
     * Successful Response
     */
    201: {
        [key: string]: string;
    };
};

export type PostRevealApiV1CalibrationPresentationsPresentationIdPostRevealPostResponse = PostRevealApiV1CalibrationPresentationsPresentationIdPostRevealPostResponses[keyof PostRevealApiV1CalibrationPresentationsPresentationIdPostRevealPostResponses];

export type LockStageApiV1CalibrationPresentationsPresentationIdLockStagePostData = {
    body?: never;
    path: {
        /**
         * Presentation Id
         */
        presentation_id: string;
        /**
         * Stage
         */
        stage: 'BLOTTER' | 'SKIN';
    };
    query?: never;
    url: '/api/v1/calibration/presentations/{presentation_id}/lock/{stage}';
};

export type LockStageApiV1CalibrationPresentationsPresentationIdLockStagePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LockStageApiV1CalibrationPresentationsPresentationIdLockStagePostError = LockStageApiV1CalibrationPresentationsPresentationIdLockStagePostErrors[keyof LockStageApiV1CalibrationPresentationsPresentationIdLockStagePostErrors];

export type LockStageApiV1CalibrationPresentationsPresentationIdLockStagePostResponses = {
    /**
     * Response Lock Stage Api V1 Calibration Presentations  Presentation Id  Lock  Stage  Post
     *
     * Successful Response
     */
    200: {
        [key: string]: boolean;
    };
};

export type LockStageApiV1CalibrationPresentationsPresentationIdLockStagePostResponse = LockStageApiV1CalibrationPresentationsPresentationIdLockStagePostResponses[keyof LockStageApiV1CalibrationPresentationsPresentationIdLockStagePostResponses];

export type SkinPlanApiV1CalibrationPresentationsPresentationIdSkinPlanPostData = {
    body: SkinPlanInput;
    path: {
        /**
         * Presentation Id
         */
        presentation_id: string;
    };
    query?: never;
    url: '/api/v1/calibration/presentations/{presentation_id}/skin-plan';
};

export type SkinPlanApiV1CalibrationPresentationsPresentationIdSkinPlanPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SkinPlanApiV1CalibrationPresentationsPresentationIdSkinPlanPostError = SkinPlanApiV1CalibrationPresentationsPresentationIdSkinPlanPostErrors[keyof SkinPlanApiV1CalibrationPresentationsPresentationIdSkinPlanPostErrors];

export type SkinPlanApiV1CalibrationPresentationsPresentationIdSkinPlanPostResponses = {
    /**
     * Response Skin Plan Api V1 Calibration Presentations  Presentation Id  Skin Plan Post
     *
     * Successful Response
     */
    200: {
        [key: string]: boolean;
    };
};

export type SkinPlanApiV1CalibrationPresentationsPresentationIdSkinPlanPostResponse = SkinPlanApiV1CalibrationPresentationsPresentationIdSkinPlanPostResponses[keyof SkinPlanApiV1CalibrationPresentationsPresentationIdSkinPlanPostResponses];

export type LockSkinPlanApiV1CalibrationEnrollmentsEnrollmentIdLockSkinPlanPostData = {
    body?: never;
    path: {
        /**
         * Enrollment Id
         */
        enrollment_id: string;
    };
    query?: never;
    url: '/api/v1/calibration/enrollments/{enrollment_id}/lock-skin-plan';
};

export type LockSkinPlanApiV1CalibrationEnrollmentsEnrollmentIdLockSkinPlanPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LockSkinPlanApiV1CalibrationEnrollmentsEnrollmentIdLockSkinPlanPostError = LockSkinPlanApiV1CalibrationEnrollmentsEnrollmentIdLockSkinPlanPostErrors[keyof LockSkinPlanApiV1CalibrationEnrollmentsEnrollmentIdLockSkinPlanPostErrors];

export type LockSkinPlanApiV1CalibrationEnrollmentsEnrollmentIdLockSkinPlanPostResponses = {
    /**
     * Response Lock Skin Plan Api V1 Calibration Enrollments  Enrollment Id  Lock Skin Plan Post
     *
     * Successful Response
     */
    200: {
        [key: string]: boolean;
    };
};

export type LockSkinPlanApiV1CalibrationEnrollmentsEnrollmentIdLockSkinPlanPostResponse = LockSkinPlanApiV1CalibrationEnrollmentsEnrollmentIdLockSkinPlanPostResponses[keyof LockSkinPlanApiV1CalibrationEnrollmentsEnrollmentIdLockSkinPlanPostResponses];

export type RevealApiV1CalibrationEnrollmentsEnrollmentIdRevealPostData = {
    body?: never;
    path: {
        /**
         * Enrollment Id
         */
        enrollment_id: string;
    };
    query?: never;
    url: '/api/v1/calibration/enrollments/{enrollment_id}/reveal';
};

export type RevealApiV1CalibrationEnrollmentsEnrollmentIdRevealPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RevealApiV1CalibrationEnrollmentsEnrollmentIdRevealPostError = RevealApiV1CalibrationEnrollmentsEnrollmentIdRevealPostErrors[keyof RevealApiV1CalibrationEnrollmentsEnrollmentIdRevealPostErrors];

export type RevealApiV1CalibrationEnrollmentsEnrollmentIdRevealPostResponses = {
    /**
     * Response Reveal Api V1 Calibration Enrollments  Enrollment Id  Reveal Post
     *
     * Successful Response
     */
    200: {
        [key: string]: boolean;
    };
};

export type RevealApiV1CalibrationEnrollmentsEnrollmentIdRevealPostResponse = RevealApiV1CalibrationEnrollmentsEnrollmentIdRevealPostResponses[keyof RevealApiV1CalibrationEnrollmentsEnrollmentIdRevealPostResponses];

export type CheckpointsApiV1CalibrationEnrollmentsEnrollmentIdCheckpointsGetData = {
    body?: never;
    path: {
        /**
         * Enrollment Id
         */
        enrollment_id: string;
    };
    query?: never;
    url: '/api/v1/calibration/enrollments/{enrollment_id}/checkpoints';
};

export type CheckpointsApiV1CalibrationEnrollmentsEnrollmentIdCheckpointsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CheckpointsApiV1CalibrationEnrollmentsEnrollmentIdCheckpointsGetError = CheckpointsApiV1CalibrationEnrollmentsEnrollmentIdCheckpointsGetErrors[keyof CheckpointsApiV1CalibrationEnrollmentsEnrollmentIdCheckpointsGetErrors];

export type CheckpointsApiV1CalibrationEnrollmentsEnrollmentIdCheckpointsGetResponses = {
    /**
     * Response Checkpoints Api V1 Calibration Enrollments  Enrollment Id  Checkpoints Get
     *
     * Successful Response
     */
    200: Array<{
        [key: string]: unknown;
    }>;
};

export type CheckpointsApiV1CalibrationEnrollmentsEnrollmentIdCheckpointsGetResponse = CheckpointsApiV1CalibrationEnrollmentsEnrollmentIdCheckpointsGetResponses[keyof CheckpointsApiV1CalibrationEnrollmentsEnrollmentIdCheckpointsGetResponses];

export type CheckpointApiV1CalibrationEnrollmentsEnrollmentIdCheckpointsPostData = {
    body: CheckpointInput;
    path: {
        /**
         * Enrollment Id
         */
        enrollment_id: string;
    };
    query?: never;
    url: '/api/v1/calibration/enrollments/{enrollment_id}/checkpoints';
};

export type CheckpointApiV1CalibrationEnrollmentsEnrollmentIdCheckpointsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CheckpointApiV1CalibrationEnrollmentsEnrollmentIdCheckpointsPostError = CheckpointApiV1CalibrationEnrollmentsEnrollmentIdCheckpointsPostErrors[keyof CheckpointApiV1CalibrationEnrollmentsEnrollmentIdCheckpointsPostErrors];

export type CheckpointApiV1CalibrationEnrollmentsEnrollmentIdCheckpointsPostResponses = {
    /**
     * Response Checkpoint Api V1 Calibration Enrollments  Enrollment Id  Checkpoints Post
     *
     * Successful Response
     */
    201: {
        [key: string]: string;
    };
};

export type CheckpointApiV1CalibrationEnrollmentsEnrollmentIdCheckpointsPostResponse = CheckpointApiV1CalibrationEnrollmentsEnrollmentIdCheckpointsPostResponses[keyof CheckpointApiV1CalibrationEnrollmentsEnrollmentIdCheckpointsPostResponses];

export type MappingApiV1CalibrationEnrollmentsEnrollmentIdMappingGetData = {
    body?: never;
    path: {
        /**
         * Enrollment Id
         */
        enrollment_id: string;
    };
    query?: never;
    url: '/api/v1/calibration/enrollments/{enrollment_id}/mapping';
};

export type MappingApiV1CalibrationEnrollmentsEnrollmentIdMappingGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type MappingApiV1CalibrationEnrollmentsEnrollmentIdMappingGetError = MappingApiV1CalibrationEnrollmentsEnrollmentIdMappingGetErrors[keyof MappingApiV1CalibrationEnrollmentsEnrollmentIdMappingGetErrors];

export type MappingApiV1CalibrationEnrollmentsEnrollmentIdMappingGetResponses = {
    /**
     * Response Mapping Api V1 Calibration Enrollments  Enrollment Id  Mapping Get
     *
     * Successful Response
     */
    200: Array<{
        [key: string]: unknown;
    }>;
};

export type MappingApiV1CalibrationEnrollmentsEnrollmentIdMappingGetResponse = MappingApiV1CalibrationEnrollmentsEnrollmentIdMappingGetResponses[keyof MappingApiV1CalibrationEnrollmentsEnrollmentIdMappingGetResponses];

export type HistoryApiV1CalibrationHistoryReviewerIdGetData = {
    body?: never;
    path: {
        /**
         * Reviewer Id
         */
        reviewer_id: string;
    };
    query?: never;
    url: '/api/v1/calibration/history/{reviewer_id}';
};

export type HistoryApiV1CalibrationHistoryReviewerIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type HistoryApiV1CalibrationHistoryReviewerIdGetError = HistoryApiV1CalibrationHistoryReviewerIdGetErrors[keyof HistoryApiV1CalibrationHistoryReviewerIdGetErrors];

export type HistoryApiV1CalibrationHistoryReviewerIdGetResponses = {
    /**
     * Response History Api V1 Calibration History  Reviewer Id  Get
     *
     * Successful Response
     */
    200: Array<{
        [key: string]: unknown;
    }>;
};

export type HistoryApiV1CalibrationHistoryReviewerIdGetResponse = HistoryApiV1CalibrationHistoryReviewerIdGetResponses[keyof HistoryApiV1CalibrationHistoryReviewerIdGetResponses];

export type ListPredictionsApiV1PredictionsGetData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Reviewer Id
         */
        reviewer_id: string;
    };
    url: '/api/v1/predictions';
};

export type ListPredictionsApiV1PredictionsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListPredictionsApiV1PredictionsGetError = ListPredictionsApiV1PredictionsGetErrors[keyof ListPredictionsApiV1PredictionsGetErrors];

export type ListPredictionsApiV1PredictionsGetResponses = {
    /**
     * Response List Predictions Api V1 Predictions Get
     *
     * Successful Response
     */
    200: Array<PredictionView>;
};

export type ListPredictionsApiV1PredictionsGetResponse = ListPredictionsApiV1PredictionsGetResponses[keyof ListPredictionsApiV1PredictionsGetResponses];

export type CreatePredictionApiV1PredictionsPostData = {
    body: PredictionCreate;
    path?: never;
    query?: never;
    url: '/api/v1/predictions';
};

export type CreatePredictionApiV1PredictionsPostErrors = {
    /**
     * Reviewer, fragrance, or checkpoint not found
     */
    404: unknown;
    /**
     * Checkpoint belongs to a different reviewer
     */
    409: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreatePredictionApiV1PredictionsPostError = CreatePredictionApiV1PredictionsPostErrors[keyof CreatePredictionApiV1PredictionsPostErrors];

export type CreatePredictionApiV1PredictionsPostResponses = {
    /**
     * Successful Response
     */
    201: PredictionView;
};

export type CreatePredictionApiV1PredictionsPostResponse = CreatePredictionApiV1PredictionsPostResponses[keyof CreatePredictionApiV1PredictionsPostResponses];

export type LinkOutcomeApiV1PredictionsPredictionIdOutcomePostData = {
    body: PredictionOutcomeInput;
    path: {
        /**
         * Prediction Id
         */
        prediction_id: string;
    };
    query?: never;
    url: '/api/v1/predictions/{prediction_id}/outcome';
};

export type LinkOutcomeApiV1PredictionsPredictionIdOutcomePostErrors = {
    /**
     * Prediction not found
     */
    404: unknown;
    /**
     * Prediction already has a different linked outcome, or the supplied outcome cannot honestly test this prediction (wrong reviewer/fragrance, recorded before the prediction, a soft-deleted reviewer/fragrance, or a predicted_scale mismatched to the outcome's scale). Retrying with the same outcome id(s) already linked is a no-op success, not a conflict.
     */
    409: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LinkOutcomeApiV1PredictionsPredictionIdOutcomePostError = LinkOutcomeApiV1PredictionsPredictionIdOutcomePostErrors[keyof LinkOutcomeApiV1PredictionsPredictionIdOutcomePostErrors];

export type LinkOutcomeApiV1PredictionsPredictionIdOutcomePostResponses = {
    /**
     * Successful Response
     */
    200: PredictionView;
};

export type LinkOutcomeApiV1PredictionsPredictionIdOutcomePostResponse = LinkOutcomeApiV1PredictionsPredictionIdOutcomePostResponses[keyof LinkOutcomeApiV1PredictionsPredictionIdOutcomePostResponses];
