"""Preserve encounter history and introduce controlled calibration.

Revision ID: c731b42e9a01
Revises: b954e9888344
"""

import sqlalchemy as sa

from alembic import op

revision = "c731b42e9a01"
down_revision = "b954e9888344"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Add controlled tables without deleting or rewriting existing observations."""
    op.drop_index("uq_evaluation_reviewer_fragrance", table_name="evaluations")
    op.drop_index("uq_fragrance_name_brand", table_name="fragrances")
    op.add_column(
        "fragrances",
        sa.Column(
            "version_key", sa.String(200), nullable=False, server_default="legacy"
        ),
    )
    op.create_index(
        "uq_fragrance_version",
        "fragrances",
        ["name", "brand", "concentration", "version_key"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL"),
        sqlite_where=sa.text("deleted_at IS NULL"),
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "calibration_perfumers",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "calibration_programs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("version", sa.String(length=50), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("locked_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name", "version"),
    )
    op.create_table(
        "calibration_enrollments",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("program_id", sa.String(length=36), nullable=False),
        sa.Column("reviewer_id", sa.String(length=36), nullable=False),
        sa.Column("recorder_usernames", sa.JSON(), nullable=False),
        sa.Column("skin_plan_locked_at", sa.DateTime(), nullable=True),
        sa.Column("revealed_at", sa.DateTime(), nullable=True),
        sa.Column("revealed_by", sa.String(length=255), nullable=True),
        sa.ForeignKeyConstraint(
            ["program_id"], ["calibration_programs.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["reviewer_id"], ["reviewers.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("program_id", "reviewer_id"),
    )
    op.create_index(
        op.f("ix_calibration_enrollments_reviewer_id"),
        "calibration_enrollments",
        ["reviewer_id"],
        unique=False,
    )
    op.create_table(
        "calibration_memberships",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("program_id", sa.String(length=36), nullable=False),
        sa.Column("fragrance_id", sa.String(length=36), nullable=False),
        sa.Column("role", sa.String(length=30), nullable=False),
        sa.Column("repeat_of_id", sa.String(length=36), nullable=True),
        sa.Column("group_name", sa.String(length=200), nullable=False),
        sa.Column("selection", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["fragrance_id"], ["fragrances.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["program_id"], ["calibration_programs.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["repeat_of_id"], ["calibration_memberships.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_calibration_memberships_fragrance_id"),
        "calibration_memberships",
        ["fragrance_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_calibration_memberships_program_id"),
        "calibration_memberships",
        ["program_id"],
        unique=False,
    )
    op.create_table(
        "calibration_source_snapshots",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("fragrance_id", sa.String(length=36), nullable=False),
        sa.Column("source_url", sa.String(length=1000), nullable=False),
        sa.Column("verification_status", sa.String(length=30), nullable=False),
        sa.Column("retrieved_at", sa.DateTime(), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["fragrance_id"], ["fragrances.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "calibration_version_perfumers",
        sa.Column("fragrance_id", sa.String(length=36), nullable=False),
        sa.Column("perfumer_id", sa.String(length=36), nullable=False),
        sa.Column("source_url", sa.String(length=1000), nullable=False),
        sa.ForeignKeyConstraint(
            ["fragrance_id"], ["fragrances.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["perfumer_id"], ["calibration_perfumers.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("fragrance_id", "perfumer_id"),
    )
    op.create_table(
        "calibration_checkpoints",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("enrollment_id", sa.String(length=36), nullable=False),
        sa.Column("algorithm_version", sa.String(length=200), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("manifest", sa.JSON(), nullable=False),
        sa.Column("predictions", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["enrollment_id"], ["calibration_enrollments.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "calibration_sessions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("enrollment_id", sa.String(length=36), nullable=False),
        sa.Column("context", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["enrollment_id"], ["calibration_enrollments.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_calibration_sessions_enrollment_id"),
        "calibration_sessions",
        ["enrollment_id"],
        unique=False,
    )
    op.create_table(
        "calibration_presentations",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("session_id", sa.String(length=36), nullable=False),
        sa.Column("membership_id", sa.String(length=36), nullable=False),
        sa.Column("blind_code", sa.String(length=24), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("skin_reason", sa.Text(), nullable=True),
        sa.Column("blotter_locked_at", sa.DateTime(), nullable=True),
        sa.Column("skin_locked_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["membership_id"], ["calibration_memberships.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["session_id"], ["calibration_sessions.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("blind_code"),
        sa.UniqueConstraint("session_id", "position"),
    )
    op.create_index(
        op.f("ix_calibration_presentations_session_id"),
        "calibration_presentations",
        ["session_id"],
        unique=False,
    )
    op.create_table(
        "calibration_observations",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("presentation_id", sa.String(length=36), nullable=False),
        sa.Column("stage", sa.String(length=20), nullable=False),
        sa.Column("phase", sa.String(length=20), nullable=False),
        sa.Column("elapsed_minutes", sa.Integer(), nullable=False),
        sa.Column("detected", sa.Boolean(), nullable=True),
        sa.Column("intensity", sa.Integer(), nullable=True),
        sa.Column("liking", sa.Integer(), nullable=True),
        sa.Column("responses", sa.JSON(), nullable=False),
        sa.Column("recorded_by", sa.String(length=255), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            "detected IS NULL OR detected OR (intensity = 0 AND intensity IS NOT NULL AND liking IS NULL)"
        ),
        sa.CheckConstraint("elapsed_minutes >= 0"),
        sa.CheckConstraint("intensity IS NULL OR (intensity >= 0 AND intensity <= 5)"),
        sa.CheckConstraint("liking IS NULL OR (liking >= 0 AND liking <= 10)"),
        sa.ForeignKeyConstraint(
            ["presentation_id"], ["calibration_presentations.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_calibration_observations_presentation_id"),
        "calibration_observations",
        ["presentation_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Refuse a lossy rollback of encounter history and experimental records."""
    message = (
        "Restore a verified pre-upgrade backup to downgrade; this migration "
        "preserves all encounters"
    )
    raise RuntimeError(message)
